// This file contains mappings for fixing lucide-react icon import errors
// Many icons that were used don't exist in the current version

export const iconReplacements = {
  // Non-existent icons -> replacement icons
  'Eye': 'Eye',
  'FullScreen': 'Maximize',
  'ExitFullScreen': 'Minimize', 
  'Cube': 'Box',
  'Sync': 'RefreshCw',
  'User': 'Users',
  'Area': 'BarChart3',
  'Scatter': 'BarChart3',
  'Seedling': 'Sprout',
  'Orange': 'Apple',
  'Strawberry': 'Apple',
  'Chicken': 'Beef',
  'Bagel': 'Cookie',
  'Pretzel': 'Cookie',
  'Honey': 'Coffee',
  'Jam': 'Coffee',
  'Bread': 'Cookie',
  'Cheese': 'Cookie',
  'Sushi': 'Fish',
  'Taco': 'Sandwich',
  'Burrito': 'Sandwich',
  'Hotdog': 'Sandwich',
  'Fries': 'Coffee',
  'Certificate': 'Award',
  'Help': 'HelpCircle',
  'Question': 'HelpCircle',
  'Warning': 'AlertTriangle',
  'Tree': 'Trees',
  'Cocktail': 'Coffee',
  'Corn': 'Wheat',
  'Lemon': 'Apple',
  'Watermelon': 'Apple',
  'Pineapple': 'Apple',
  'Coconut': 'Apple',
  'Avocado': 'Apple',
  'Broccoli': 'Leaf',
  'Pepper': 'Carrot',
  'Mushroom': 'Leaf',
  'Onion': 'Carrot',
  'Garlic': 'Carrot',
  'Potato': 'Carrot',
  'Tomato': 'Apple',
  'Cucumber': 'Carrot',
  'Lettuce': 'Leaf',
  'Sort': 'ArrowUpDown',
  'Cut': 'Scissors',
  'Paste': 'Clipboard',
  'Outbox': 'Send',
  'Exclamation': 'AlertTriangle',
  'Stop': 'Square',
  'Stopwatch': 'Clock',
  'Random': 'Shuffle',
  'Casino': 'Dice6',
  'Touchpad2': 'Touchpad',
  'CloudSync': 'Cloud',
  'FilePdf': 'FileText',
  'FilePresentation': 'FileText',
  'Line': 'TrendingUp',
  'BarChart': 'BarChart3'
};